### PR TITLE
builder: add more options for CPU topology

### LINKED ISSUE #55: Change the default CPU topology given to QEMU when numCpus > 1
#### Overview of the Issue

When creating a QEMU virtual machine with more than one cpu, (`"cpus": "8",` in the given json file), packer will spawn QEMU with the following argument: `-smp cpus=8,sockets=8` which is equivalent to exposing 8 physical 1 core CPUs to the virtual machine. While this is fine for most operating systems, windows does not like that at all. On a non workstation installation, it will cap the CPU number to 2 which means you try giving it as many CPUs as you want, it will always see 2 of them. 

#### Reproduction Steps

Use the QEMU provider with `"cpus": "8",`.

### Packer version

Packer v1.7.8

### Simplified Packer Template

https://github.com/StefanScherer/packer-windows/blob/da1d60b0cd97ff7a9bdeb67a7612ec7c8169869b/windows_10.json and just changes cpus to 8.

###  References

The line that sets up the CPU topology is here. https://github.com/hashicorp/packer-plugin-qemu/blob/e47a7a53d628a46f5257bd92ce4d262e67a856c5/builder/qemu/step_run.go#L149

Same issue in virt-manager: https://github.com/virt-manager/virt-manager/issues/155

### Possible resolution

Change to `-smp 8,sockets=1,cores=8` by default

### PR DESCRIPTION
**Pull request by lbajolet-hashicorp**
In order to mirror more closely the options offered by qemu when it comes to expressing the topology of the SMP architecture we are building an image upon, we add more options to the configuration supported by the plugin.

In addition to cpus, we now support sockets, cores and threads. These may be used in conjunction with the cpus, or left to be computed by the plugin directly.

By default, any configuration which only defined cpus will work potentially differently from before, since this is supported by qemu, but the behaviour changes depending on the version.

Closes #55

### CODE REVIEW

**Comment by nywilken** [comment]
> By default, any configuration which only defined cpus will work potentially differently from before, since this is supported by qemu, but the behaviour changes depending on the version.

By configuration do you mean Packer template configuration? If so, I take this to mean that it will change behavior for a user, and that we will need to bump the minor version for this change. Is that correct?

**Comment by lbajolet-hashicorp** [comment]
With the new code it will indeed potentially change the behaviour for clients, since what we specified with `cpus` before used to set the cpus and sockets to the value given by the user.
This PR changes this to fallback on qemu's default behaviour when it comes to interpret `smp=%d`. This changes depending on the version of qemu:

* before v6.2, it would behave as we defined it earlier, the number of sockets will be set to `cpus`, each socket with 1 core/thread, so that would be equivalent to set `-smp cpus=%d,sockets=%d,cores=1,threads=1`.
* 6.2 and onwards, the default preference goes to cores instead of sockets, hence the `cpus` will be equivalent to set `-smp cpus=%d,sockets=1,cores=%d,threads=1`.

So depending on the version of qemu, this may not change the topology reported by the system, and more fundamentally, the number of vCPUs exposed to the guest OS will remain the same.

**Comment by lbajolet-hashicorp** [comment]
I guess it could mean a minor bump though because of the behaviour change, you are right on that.

File: builder/qemu/config.go [hunk 1]
```diff
@@ -65,6 +65,96 @@ type QemuImgArgs struct {
...
+		smpStr = fmt.Sprintf("%s,cores=%d", smpStr, c.CoreCount)
+	}
+	if c.ThreadCount > 0 {
+		smpStr = fmt.Sprintf("%s,threads=%d", smpStr, c.ThreadCount)
+	}
+
+	return smpStr
+}
+
+func (c QemuSMPConfig) getMaxCPUs() int {
```
Comment (nywilken) [inline builder/qemu/config.go:136]: Even though this is a unexported method I recommend adding comment to explain how getMaxCPUs works. More specifically that it calculates the max cpu based off the QemuSMPConfig values. At first I thought that it was making a call to the underlying system to determine max allowed cpu.

File: builder/qemu/config.go [hunk 2]
```diff
@@ -65,6 +65,96 @@ type QemuImgArgs struct {
...
+
+	if c.ThreadCount > 0 {
+		if totalVCPUs == 0 {
+			totalVCPUs = c.ThreadCount
+		} else {
+			totalVCPUs *= c.ThreadCount
+		}
+	}
+
+	return totalVCPUs
```
Comment (nywilken) [inline builder/qemu/config.go:155]: nit: The nested if statements is a little confusing. Does something like the following make it clearer? 
```suggestion
	totalVCPUs := c.SocketCount

        if totalVCPUs > 0 && c.CoreCount > 0 {
          totalVCPUs *= c.CoreCount
        } 
        
        // If number of sockets were not provided take the number of cores
        if totalVCPUs == 0 {
            totalVCPUs = c.CoreCount
        }
        
        // CPUCount, SocketCount, and ThreadCount were set return the final product of all.
        if totalVCPUs > 0 && c.ThreadCount > 0 {
               return totalVCPUs *= c.ThreadCount
        } 
        
        // If nothing else was set take the value set for thread count
	if totalVCPUs == 0 {
		return c.ThreadCount
	}

	return totalVCPUs
```

File: builder/qemu/config.go [hunk 3]
```diff
@@ -65,6 +65,96 @@ type QemuImgArgs struct {
...
+		cpuCount = totalVCpus
+	}
+
+	if totalVCpus > cpuCount {
+		log.Print("CPU count lower than what's described in topology." +
+			"This will negatively impact performance.")
+	}
+
+	if cpuCount > totalVCpus && totalVCpus != 0 {
+		log.Printf("CPU count greater than what topology allows, setting to %d", totalVCpus)
```
Comment (nywilken) [inline builder/qemu/config.go:118]:
```suggestion
		log.Printf("CPU count is greater than what topology allows, setting to CPU count to the allowed topology %d", totalVCpus)
```

File: builder/qemu/config.go [hunk 4]
```diff
@@ -65,6 +65,96 @@ type QemuImgArgs struct {
...
+// The smp option sets the number of vCPUs to expose to the VM, the final
+// number of available vCPUs is sockets*cores*threads.
+type QemuSMPConfig struct {
+	// The number of virtual cpus to use when building the VM.
+	//
+	// If undefined, the value will either be `1`, or the product of
+	// `sockets * cpus * threads`
+	//
+	// If both any topology element, or this is set, the final value will be the
+	// largest of the two.
```
Comment (nywilken) [inline builder/qemu/config.go:79]: It is not clear to me me which topology elements are being referred to here. Could you reword to call out which elements you are referring to.

**Review by nywilken — COMMENTED** [review]
Overall this looks good. I left a couple of nitpicky suggestions and a request for clarification on the comment for CPUCount.

**Review by nywilken — APPROVED** [review]
LGTM
